// Code generated by protoc-gen-av. DO NOT EDIT.
// source: demo.proto

package simple

import (
	"context"
	"regexp"
)

type CreateErrFunc func(string) error
type DemoServiceServerImpl struct {
	svc DemoServiceServer
	cef CreateErrFunc
}

func NewDemoServiceServerImpl(svc DemoServiceServer, cef CreateErrFunc) *DemoServiceServerImpl {
	return &DemoServiceServerImpl{svc: svc, cef: cef}
}

var pingPongNameRegexp = regexp.MustCompile("^[a-zA-Z][a-zA-Z0-9_]{4,15}$")

func (m *DemoServiceServerImpl) PingPong(ctx context.Context, req *Ping) (*Pong, error) {
	if req.Name == "" {
		return nil, m.cef("name can not empty")
	}
	if req.Name != "321" {
		return nil, m.cef("name must eq 321")
	}
	if req.Name != "1" && req.Name != "2" && req.Name != "3" {
		return nil, m.cef("name must in [1,2,3]")
	}
	if !pingPongNameRegexp.MatchString(req.Name) {
		return nil, m.cef("name regexp verification failed")
	}
	if req.Age == 0 {
		return nil, m.cef("age can not empty")
	}
	if req.Age <= 18 {
		return nil, m.cef("age must > 18")
	}
	if req.Age >= 200 {
		return nil, m.cef("age must < 200")
	}
	return m.svc.PingPong(ctx, req)
}
