// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugin.proto

package plugin

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Validator struct {
	NotEmpty             bool     `protobuf:"varint,1,opt,name=notEmpty,proto3" json:"notEmpty,omitempty"`
	Gte                  float64  `protobuf:"fixed64,2,opt,name=gte,proto3" json:"gte,omitempty"`
	Gt                   float64  `protobuf:"fixed64,3,opt,name=gt,proto3" json:"gt,omitempty"`
	Lte                  float64  `protobuf:"fixed64,4,opt,name=lte,proto3" json:"lte,omitempty"`
	Lt                   float64  `protobuf:"fixed64,5,opt,name=lt,proto3" json:"lt,omitempty"`
	Lq                   float64  `protobuf:"fixed64,6,opt,name=lq,proto3" json:"lq,omitempty"`
	Eq                   float64  `protobuf:"fixed64,7,opt,name=eq,proto3" json:"eq,omitempty"`
	StringEq             string   `protobuf:"bytes,8,opt,name=stringEq,proto3" json:"stringEq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Validator) Reset()         { *m = Validator{} }
func (m *Validator) String() string { return proto.CompactTextString(m) }
func (*Validator) ProtoMessage()    {}
func (*Validator) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{0}
}

func (m *Validator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Validator.Unmarshal(m, b)
}
func (m *Validator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Validator.Marshal(b, m, deterministic)
}
func (m *Validator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Validator.Merge(m, src)
}
func (m *Validator) XXX_Size() int {
	return xxx_messageInfo_Validator.Size(m)
}
func (m *Validator) XXX_DiscardUnknown() {
	xxx_messageInfo_Validator.DiscardUnknown(m)
}

var xxx_messageInfo_Validator proto.InternalMessageInfo

func (m *Validator) GetNotEmpty() bool {
	if m != nil {
		return m.NotEmpty
	}
	return false
}

func (m *Validator) GetGte() float64 {
	if m != nil {
		return m.Gte
	}
	return 0
}

func (m *Validator) GetGt() float64 {
	if m != nil {
		return m.Gt
	}
	return 0
}

func (m *Validator) GetLte() float64 {
	if m != nil {
		return m.Lte
	}
	return 0
}

func (m *Validator) GetLt() float64 {
	if m != nil {
		return m.Lt
	}
	return 0
}

func (m *Validator) GetLq() float64 {
	if m != nil {
		return m.Lq
	}
	return 0
}

func (m *Validator) GetEq() float64 {
	if m != nil {
		return m.Eq
	}
	return 0
}

func (m *Validator) GetStringEq() string {
	if m != nil {
		return m.StringEq
	}
	return ""
}

var E_Validator = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.FieldOptions)(nil),
	ExtensionType: (*Validator)(nil),
	Field:         50002,
	Name:          "plugin.validator",
	Tag:           "bytes,50002,opt,name=validator",
	Filename:      "plugin.proto",
}

func init() {
	proto.RegisterType((*Validator)(nil), "plugin.Validator")
	proto.RegisterExtension(E_Validator)
}

func init() { proto.RegisterFile("plugin.proto", fileDescriptor_22a625af4bc1cc87) }

var fileDescriptor_22a625af4bc1cc87 = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x49, 0x57, 0x6b, 0x1b, 0x45, 0xb4, 0xa7, 0x61, 0x41, 0x28, 0x9e, 0x7a, 0xca, 0x82,
	0xde, 0xbc, 0xaf, 0x57, 0xa5, 0x07, 0xef, 0xbb, 0x36, 0x86, 0xc0, 0xd8, 0x49, 0xd2, 0x59, 0xc1,
	0x17, 0xf0, 0x55, 0x7c, 0x1f, 0x9f, 0x48, 0x92, 0xac, 0xf1, 0x96, 0x6f, 0xf8, 0x92, 0xfc, 0xff,
	0xc8, 0x0b, 0x87, 0x07, 0x63, 0x67, 0xe5, 0x02, 0x31, 0x75, 0x75, 0xa6, 0x75, 0x6f, 0x88, 0x0c,
	0xea, 0x4d, 0x9a, 0xee, 0x0f, 0x6f, 0x9b, 0x49, 0x2f, 0xaf, 0xc1, 0x3a, 0xa6, 0x90, 0xcd, 0xdb,
	0x6f, 0x21, 0xdb, 0x97, 0x1d, 0xda, 0x69, 0xc7, 0x14, 0xba, 0xb5, 0x6c, 0x66, 0xe2, 0xed, 0xbb,
	0xe3, 0x4f, 0x10, 0xbd, 0x18, 0x9a, 0xb1, 0x70, 0x77, 0x25, 0x57, 0x86, 0x35, 0x54, 0xbd, 0x18,
	0xc4, 0x18, 0x8f, 0xdd, 0xa5, 0xac, 0x0c, 0xc3, 0x2a, 0x0d, 0x2a, 0xc3, 0xd1, 0x40, 0xd6, 0x70,
	0x92, 0x0d, 0xcc, 0x06, 0x32, 0x9c, 0x66, 0x03, 0x39, 0xb1, 0x87, 0xfa, 0xc8, 0x3e, 0xb2, 0xf6,
	0x70, 0x96, 0x59, 0xfb, 0xf8, 0xff, 0xc2, 0xc1, 0xce, 0x66, 0xeb, 0xa1, 0xe9, 0xc5, 0xd0, 0x8e,
	0x85, 0x1f, 0x9e, 0x65, 0xfb, 0x51, 0x82, 0xde, 0xa8, 0xdc, 0x4c, 0xfd, 0x35, 0x53, 0x8f, 0x56,
	0xe3, 0xf4, 0xe4, 0xd8, 0xd2, 0xbc, 0xc0, 0xcf, 0x57, 0x4c, 0x75, 0x7e, 0x77, 0xad, 0x8e, 0x6b,
	0x29, 0x15, 0xc7, 0xff, 0x47, 0xf6, 0x75, 0xba, 0x7c, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x53,
	0x5f, 0x13, 0x04, 0x3c, 0x01, 0x00, 0x00,
}
